# Версия docker-compose
version: "3"

# Список контейнеров
services:

  # Контейнер с базой данных
  db:
    # Имя контейнера
    container_name: "postgres-db"

    # Взять готовый образ `postgres`
    image: "postgres:12-alpine"

    # Зеркальная папка с БД
    # Если вы хотите использовать данные из реальной БД(которая вне контейнера)
    # То установите путь
    volumes:
      - "${POSTGRES_VOLUMES}:/var/lib/postgresql/data"

    # Взять переменные окружения
    env_file: ${PATH_ENV}


##########
# # Версия docker-compose
# version: "3"

# # Список контейнеров
# services:

#   # Контейнер с базой данных
#   db:
#     # Имя контейнера
#     container_name: "postgres-db"

#     # Взять готовый образ `postgres` 
#     image: "postgres"

#     # Зеркальная папка с БД
#     # Если вы хотите использовать данные из реальной БД(которая вне контейнера)
#     # То установите путь 
#     volumes:
#       - "${POSTGRES_VOLUMES}:/var/lib/postgresql/data"

#     # Взять переменные окружения
#     env_file: ${PATH_ENV}

#   # WEB контейнер
#   name_web:
#     # Имя контейнера
#     container_name: "djnago-web"

#     # Найти Dockerfile(по указанному пути) и собрать контейнер
#     build:
#       # Путь к `Dockerfile`
#       context: .
#       # Передать аргумент в `Dockerfile` с путем к рабочей деректории
#       args:
#         WORK_DIR: ${WORK_DIR}

#     # Путь к файлу с переменными окружениями  (Эти переменные будут доступны во всем контейнере)
#     env_file: ${PATH_ENV}

#     # Зеркальная папка с Проектом
#     volumes:
#       - ".:${WORK_DIR}"

#     # # Не будем пробрасывать порты между реальной машиной и контейнером
#     # ports:
#     #   - "${EXTERNAL_WEB_PORT}:8009"

#     # Разрешим контейнеру обробатывать запрос с указанного порта. Это нужно для переадресацци
#     # (проксирования) с `nginx` контейнера в `web` контейнер
#     expose:
#       - ${EXTERNAL_WEB_PORT}

#     # Зависит от БД
#     depends_on:
#       - db

#   # Контейнер `Nginx`
#   name_ngix:
#     # Имя контейнера
#     container_name: "nginx-web"

#     # Путь для сбора образа
#     build: ./nginx

#     # Проброска портов
#     ports:
#       - ${NGINX_PORT}:${NGINX_PORT}

#     # Путь к файлу с переменными окружениями  (Эти переменные будут доступны во всем контейнере)
#     env_file: ${PATH_ENV}

#     # Зависит от `web` приложения
#     depends_on:
#       - name_web
