# Generated by Django 3.2.9 on 2021-11-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoproduct',
            options={'ordering': ['pk'], 'verbose_name': 'Фото продукта', 'verbose_name_plural': 'Фотки продукта'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default=0, verbose_name='Опубликованное'),
            preserve_default=False,
        ),
    ]
