# Generated by Django 3.2.9 on 2021-11-20 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211117_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория товара')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Слаг категории')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='id_category_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='mainapp.categoryproduct'),
            preserve_default=False,
        ),
    ]
