# Generated by Django 3.2.9 on 2021-11-20 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211120_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_category_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.categoryproduct', verbose_name='Имя категории'),
        ),
    ]
