# Generated by Django 3.2.9 on 2021-11-29 15:47

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211120_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproduct',
            name='path_photo',
            field=models.ImageField(max_length=600, upload_to=mainapp.models.user_directory_path, verbose_name='Изображения'),
        ),
    ]
